package com.ara.bbtgroup.rest;


import com.ara.bbtgroup.entities.User;
import com.ara.bbtgroup.entities.UserRepository;
import com.ara.bbtgroup.model.request.UserRequest;
import com.ara.bbtgroup.model.response.UserResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(ResourceConstants.EMPLOYEE_V1)
public class UserResource {

    @Autowired
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    // ======================================
    // =             GET METHOD             =
    // ======================================

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<User> getAllUsers() {

        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String firstname
            , @RequestParam String lastname) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setFirstname(firstname);
        n.setLastname(lastname);
        userRepository.save(n);
        return "Saved";
    }


    @RequestMapping(path = "", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public ResponseEntity<UserResponse> getEmployee() {

        return new ResponseEntity<>(new UserResponse("Test", "Test"),HttpStatus.OK);
    }

    // ======================================
    // =             POST METHOD            =
    // ======================================

    @RequestMapping(path = "", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_UTF8_VALUE, consumes = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public ResponseEntity<UserResponse> createUser(
            @RequestBody UserRequest userRequest){

        return new ResponseEntity<>(new UserResponse(), HttpStatus.CREATED);
    }

    // ======================================
    // =             PUT METHOD             =
    // ======================================

    @RequestMapping(path = "", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_UTF8_VALUE,
            consumes = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public ResponseEntity<UserResponse> udpateUser(
            @RequestBody
                    UserRequest userRequestRequest) {

        return new ResponseEntity<>(new UserResponse(), HttpStatus.OK);
    }

    // ======================================
    // =          DELETE METHOD             =
    // ======================================

    @RequestMapping(path = "/{userId}", method = RequestMethod.DELETE)
    public ResponseEntity<Void> delteUser(
            @PathVariable
                    Integer reservationId) {

        return new ResponseEntity<Void>(HttpStatus.NO_CONTENT);
    }
}
